### ISSUE TITLE
Error: Invalid format. Cannot read property 'short' of undefined

### ISSUE THREAD

**Issue by panta82** [ozio/kaifu#2]
```
Error: Invalid format. Cannot read property 'short' of undefined
TypeError: Cannot read property 'short' of undefined
    at unpack (/home/panta/dev/contrib/in-creator/node_modules/kaifu/src/unpack.js:125:14)
    at async runner (/home/panta/dev/contrib/in-creator/node_modules/kaifu/src/runner.js:55:11)
    at async /home/panta/dev/contrib/in-creator/node_modules/kaifu/src/cli.js:92:5
```

The problem is this line:
https://github.com/ozio/kaifu/blame/5a8cb0263ef5e094b4c4cfa1f71c6149cbf85519/src/unpack.js#L15

```
const { flags } = options;
```

Flags get destructured out of options before options are mutated.

**Comment by ozio** [comment]
Fixed! Sorry for the late answer. I don't know why, but I didn't receive a notification.

Thank you!
